#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  7 01:15:39 2022

@author: gabriel00724
"""

def recurse_fact(n):
    '''
    Returns the factorial of n
    
    '''
    if n == 1 or n == 0:
        return 1
    else:
        return n * recurse_fact(n-1)

value = int(input("Enter an integer: "))
print("The factorial of", value, "is", recurse_fact(value) )