#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  7 01:15:39 2022

@author: gabriel00724
"""

def recurse_exp(base, exp):
     '''
     Returns the factorial of n
     
     '''
     if exp == 1:
         return base
     else:
         return base * recurse_exp(base, exp - 1)
     
base = int(input("Enter an integer(base): "))
exp = int(input("Enter an integer(exp): "))
print("\n" + str(base), "to the power of " + str(exp), "is " +str(recurse_exp(base, exp)))