#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  7 21:05:29 2022

@author: gabriel00724
"""

def recurse_fib(x):
    
    if x == 1 or x == 0:
        return 1
    else:
        return recurse_fib(x-1) + recurse_fib(x-2)
    
x = int(input("Input a number: "))
print("The " + str(x) +"th fibonacci number is "+ str(recurse_fib(x)))